✨ (core) [DSDK-440]: Connect to Ledger Ble Device
LedgerHQ/device-sdk-ts pull request #221
Opened 2024-08-30 16:24 UTC by jdabbech-ledger

### 📝 Description

Based on `chore/no-issue-mockserver`
- Ble transport
- Ble disconnection and  reconnection (open app reconnects the device)

### ❓ Context

- **JIRA or GitHub link**: [DSDK-440] [DSDK-203] 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

https://github.com/user-attachments/assets/d7103ebf-76e5-41df-9c91-204cfe74efa6

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

[DSDK-440]: https://ledgerhq.atlassian.net/browse/DSDK-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DSDK-203]: https://ledgerhq.atlassian.net/browse/DSDK-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-15 13:24 UTC, valpinkman requested changes
Some questions and changes still, but close :)

2024-10-15 13:24 UTC, valpinkman commented on packages/core/src/internal/transport/ble/transport/WebBleTransport.ts
> +      .run();
[ASK] Is run really needed here ?

2024-10-15 13:24 UTC, valpinkman commented on packages/core/src/internal/transport/ble/transport/WebBleTransport.ts
> +  private async promptDeviceAccess(): Promise<
[COULD] The return type could probably be `EitherAsync<PromptDeviceAccessError, BluetoothDevice>`

2024-10-15 13:24 UTC, valpinkman commented on packages/core/src/internal/transport/model/Errors.ts
> +    if (err instanceof Error) {
[ASK] Can't we handle this in the GeneralSdkError instead of repeating it ? It would be called by the `super(err)` called thus preventing us from repeating this behavior everywhere. WDYT ?

2024-10-17 10:12 UTC, valpinkman approved these changes
Awesome 🔥

2024-10-18 08:44 UTC, mbertin-ledger approved these changes

2024-10-18 12:22 UTC, merged