Feat/dsdk 504 listen to known devices
LedgerHQ/device-sdk-ts pull request #392
Opened 2024-10-11 15:07 UTC by ofreyssinet-ledger

### 📝 Description

wip

### ❓ Context

- **JIRA or GitHub link**:

- **Feature**:

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [ ] **Covered by automatic tests** 
- [ ] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-10-18 08:09 UTC, jdabbech-ledger requested changes
Good rework of the transport hid
A lot of modifications in the sample app sdk provider as well, but there are few bugs when switching transport between mock and hid (by connecting device in the meantime). Moreover some e2e tests seem to be broken

2024-10-18 09:53 UTC, jdabbech-ledger commented on packages/core/src/internal/transport/usb/transport/WebUsbHidTransport.ts
> +  private async updateInternalDiscoveredDevices() {
[could] specify return value

2024-10-18 09:55 UTC, jdabbech-ledger commented on packages/core/src/internal/transport/usb/transport/WebUsbHidTransport.ts
> +    await this.getDevices().then((either) => {
[ask] wouldn't it be clearer to not use `.then` if using `await` syntax?
[could] use EitherAsync

2024-10-18 15:40 UTC, ofreyssinet-ledger commented on apps/sample/src/providers/DeviceSdkProvider/index.tsx
> +      state.sdk.close();
The error when enabling mock server was due to something else. The part of the app listen to each session state was still calling getDeviceSessionState() with a invalid sessionId (when the SDK has been closed) and it was uncaught in a useEffect so it was actually crashing the app.
And there's probably some error boundary in Next remounting the app, but the state was not preserved, hence the fact that you had to toggle the mock server mode once again.
It's not happening anymore because now in the `DeviceSessionsProvider` we cleanup the state whenever the `sdk` obtained through `useSdk` changes.

The "it's called called too many times" is because of React Strict Mode in dev mode which runs effects an extra time. It's working fine now 👍

2024-10-22 08:26 UTC, jdabbech-ledger approved these changes

2024-10-23 09:13 UTC, valpinkman approved these changes

2024-10-23 12:47 UTC, aussedatlo approved these changes

2024-10-23 13:13 UTC, merged