✨ (keyring-eth) [DSDK-521]: Adapt SignTransactionCommand + new StoreTransactionCommand
LedgerHQ/device-sdk-ts pull request #418
Opened 2024-10-16 13:25 UTC by valpinkman

### 📝 Description

Add support to SignTransaction for the incoming version of Ethereum app 1.13

### ❓ Context

- **JIRA or GitHub link**: [DSK-521]

- **Feature**:

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [x] **Covered by automatic tests** 
- [x] **Changeset is provided** 
- [x] **Impact of the changes:** 
  - Adapt SignTransactionCommand
  - Add StoreTransactionCommand
  - Update SendSignTransactionTask to use legacy mode by default

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-10-16 14:40 UTC, jdabbech-ledger commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.test.ts
> +  describe("Legacy", () => {
[could] 
```suggestion
describe("getApdu", () => {
  describe("Legacy", ...);
  describe("Store and start", ...);
  describe("Start", ...);
})
```

2024-10-16 14:42 UTC, jdabbech-ledger commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.test.ts
> +    // TODO
[could] add tests?

2024-10-16 14:47 UTC, jiyuzhuang commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.ts
> +    return 0x03;
1. If the ["store only"(0x02)](https://github.com/LedgerHQ/generic_parser/blob/master/specs.md#sign) does not need to be handled here, it's OK;
2. Enum default value can be used here:
```suggestion
return flow === SignTransactionFlow.START ? 0x03 : flow;
```

2024-10-16 14:49 UTC, jiyuzhuang commented on packages/signer/keyring-eth/src/internal/app-binder/command/StoreTransactionCommand.ts
> +  }
[COULD] Recommended 
```suggestion
  constructor(private readonly args: StoreTransactionCommandArgs) {}
```

2024-10-16 15:04 UTC, paoun-ledger commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.ts
> +    return 0x03;
not sure if it's better but it could also be a const mapping such as:

    const FLOW_TO_P2: Record<SignTransactionFlow, number> = {
      [SignTransactionFlow.LEGACY]: 0x00,
      [SignTransactionFlow.STORE_AND_START]: 0x01,
      [SignTransactionFlow.START]: 0x03,
    };

2024-10-16 15:07 UTC, paoun-ledger commented on packages/signer/keyring-eth/src/internal/app-binder/command/StoreTransactionCommand.ts
> +      p1: isFirstChunk ? 0x00 : 0x80,
```suggestion
      p1: isFirstChunk ? 0x01 : 0x00,
```

2024-10-16 15:10 UTC, paoun-ledger commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.ts
>      return builder.addBufferToData(serializedTransaction).build();
according to https://github.com/LedgerHQ/generic_parser/blob/master/specs.md#command-data
if the flow is `SignTransactionFlow.START`, then no serialized transaction is provided (it was already provided in the store command)

2024-10-16 15:23 UTC, valpinkman commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.test.ts
> +  describe("Legacy", () => {
Yeah, one way or another it's the same i guess.

2024-10-16 15:24 UTC, valpinkman commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.test.ts
> +    // TODO
Not yet, the ETH App is not released yet, we do no have the data to test.
Also, as explained in the PR, the test will come in another PR

2024-10-16 15:26 UTC, valpinkman commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.ts
>      return builder.addBufferToData(serializedTransaction).build();
From what @aussedatlo told me, it seems like we pass the transaction again. I need to check with him again

2024-10-16 15:26 UTC, valpinkman commented
I will look back in the feedback with @aussedatlo tomorrow and will update everything accordingly. Thank you for the feedback 🙏

2024-10-16 15:29 UTC, valpinkman commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.ts
> +    return 0x03;
@jiyuzhuang the store is handle in another command StoreTransaction it "cannot" be handle here.

@paoun-ledger if we need more "logic", the function can handle it better than just the object

2024-10-16 15:30 UTC, valpinkman commented on packages/signer/keyring-eth/src/internal/app-binder/command/StoreTransactionCommand.ts
> +      p1: isFirstChunk ? 0x00 : 0x80,
Thanks for the catch

2024-10-16 15:33 UTC, valpinkman commented on packages/signer/keyring-eth/src/internal/app-binder/command/StoreTransactionCommand.ts
> +  }
updated 👍

2024-10-16 15:34 UTC, valpinkman commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.ts
>      return builder.addBufferToData(serializedTransaction).build();
You are right, I've updated the method. Thanks

2024-10-16 16:16 UTC, paoun-ledger commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.ts
> +  readonly flow: SignTransactionFlow;
[COULD] detail but maybe we could improve the typing for the case when `flow == START`, to avoid being forced to give an empty (and unused) transaction in parameters ?
Something like:

    type SignTransactionCommandArgs =
      | {
          readonly flow: SignTransactionFlow.START;
        }
      | {
          /**
           * The transaction to sign in max 150 bytes chunks
           */
          readonly serializedTransaction: Uint8Array;
          /**
           * If this is the first chunk of the message
           */
          readonly isFirstChunk: boolean;
          /**
           * If we are using the legacy flow
           */
          readonly flow: Exclude<SignTransactionFlow, SignTransactionFlow.START>;
        };

2024-10-17 07:55 UTC, mbertin-ledger requested changes
Look at my comment
As we have storeCommand, I'm asking myself if we should not create the other one, so having 3 different command for Storing, Process and StoreAndProcess SignCommand (we already have 2), It could allow have constant stuff and maye simplify command readability ? WDYT ?

2024-10-17 08:47 UTC, aussedatlo commented on packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.ts
> +}
Yes indeed, to improve typing it's better and easier to split in 3 command. However, the naming is a bit strange on the doc, since `process` is in fact `store`.
So we have 3 case
- StoreAndStartCommand (or ProcessAndStartCommand) -> transaction in input, signature in return
- StoreCommand -> transaction in input -> nothing in return
- StartCommand -> noting in input -> signature in return

2024-10-17 09:29 UTC, jdabbech-ledger approved these changes

2024-10-17 09:35 UTC, ofreyssinet-ledger commented on packages/signer/keyring-eth/src/internal/app-binder/command/StartTransactionCommand.ts
> + * StoreTransactionCommand is a SignTransactionCommand that is used to initiate
[SHOULD] typo: `StartTransactionCommand`

2024-10-17 09:35 UTC, ofreyssinet-ledger approved these changes

2024-10-17 12:04 UTC, valpinkman commented on packages/signer/keyring-eth/src/internal/app-binder/command/StartTransactionCommand.ts
> + * StoreTransactionCommand is a SignTransactionCommand that is used to initiate
thanks 👍

2024-10-17 12:16 UTC, mbertin-ledger approved these changes

2024-10-17 12:17 UTC, merged