✨ (sample) [DSDK-539]: Add keyring eth provider
LedgerHQ/device-sdk-ts pull request #431
Opened 2024-10-21 07:51 UTC by aussedatlo

### 📝 Description

Add a provider for the keyring eth. Allow the modification of the CAL config, and reload the keyring if the configuration change.

### ❓ Context

- **JIRA or GitHub link**:

[DSDK-539]

- **Feature**:

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [ ] **Covered by automatic tests** 
- [x] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-10-21 12:07 UTC, valpinkman commented on apps/sample/src/app/client-layout.tsx
> +        <DeviceSessionsProvider>
[COULD] The DeviceSessionProvider could be after the SdkProvider since it needs it ?

2024-10-21 12:11 UTC, valpinkman commented on apps/sample/src/providers/KeyringEthProvider/index.tsx
> +    console.log("Creating keyring with session id", sessionId);
[COULD] Nice for debugging, maybe not necessary for prod

2024-10-21 12:36 UTC, aussedatlo commented on apps/sample/src/app/client-layout.tsx
> +        <DeviceSessionsProvider>
yes, rebase problem, fixed now 👍

2024-10-23 10:21 UTC, jdabbech-ledger requested changes

2024-10-23 10:21 UTC, jdabbech-ledger commented on apps/sample/src/components/CalView/CalSettingsDrawer.tsx
> +import { Button, Divider, Flex } from "@ledgerhq/react-ui/index";
index 🧐

2024-10-23 11:59 UTC, jdabbech-ledger approved these changes

2024-10-24 12:24 UTC, merged