✨ (signer-solana) [DSDK-554]: Add GetAddressUseCase
LedgerHQ/device-sdk-ts pull request #451
Opened 2024-10-28 13:01 UTC by aussedatlo

### 📝 Description

Add `GetAddressUseCase` implementation for the `signer-solana`.
Add signer view in the playground app.

### ❓ Context

- **JIRA or GitHub link**: [DSDK-554]

- **Feature**:

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [x] **Covered by automatic tests** 
- [x] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-10-28 13:29 UTC, jdabbech-ledger approved these changes

2024-10-28 18:33 UTC, mbertin-ledger requested changes

2024-10-28 18:33 UTC, mbertin-ledger commented on apps/sample/src/components/SignerSolanaView/index.tsx
> +          "Perform all the actions necessary to get an ethereum address from the device",
[MUST] Use Solana 

⚠️ copy paste !

2024-10-28 18:33 UTC, mbertin-ledger commented on apps/sample/src/components/SignerSolanaView/index.tsx
> +          derivationPath: "44'/501'",
[SHOULD] Defaut Value should be a constant

2024-10-28 18:33 UTC, mbertin-ledger commented on apps/sample/src/components/SignerSolanaView/index.tsx
> +    <DeviceActionsList title="Keyring Ethereum" deviceActions={deviceActions} />
[MUST] Same here copy paste => `Signer Solana `

2024-10-29 12:44 UTC, mbertin-ledger approved these changes
👍 
Just a remark, as we are getting the pubKey shouldn't we call it getPubKey ?

2024-10-29 12:54 UTC, aussedatlo commented
> 👍 Just a remark, as we are getting the pubKey shouldn't we call it getPubKey ?

Unlike Ethereum, where the address is derived from the public key, Solana uses the public key directly as the address. To maintain consistency with the Ethereum signer, I’ve retained the `getAddress` method name.

2024-10-29 14:03 UTC, merged