:truck: (core) [DSDK-570]: [TS][DMK] Rename classes
LedgerHQ/device-sdk-ts pull request #460
Opened 2024-10-30 13:43 UTC by jdabbech-ledger

### 📝 Description

Rename Keyring into Signer 
- KeyringEth => SignerEth
- KeyringBtc => SignerBtc
- Every keyring related file/variable names

Rename Sdk to Dmk
- Entrypoint DeviceSDK => DeviceManagement 
- Every sdk related file/variable names 

### ❓ Context

- **JIRA or GitHub link**: [DSDK-570]

- **Feature**:

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [x] **Covered by automatic tests** 
- [x] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-10-30 14:18 UTC, aussedatlo reviewed
Don't forget tu update the signer ethereum readme.
Also I was thinking, we usr `btc`, `eth` but `solana` instead of `sol`. Should we plan to change this also ?

2024-10-30 14:35 UTC, aussedatlo requested changes

2024-10-30 14:35 UTC, aussedatlo commented on packages/signer/signer-btc/package.json
[MUST] Replace the old name `@ledgerhq/keyring-btc`

2024-10-30 14:35 UTC, aussedatlo commented on package.json
> +    "signer-btc": "pnpm --filter @ledgerhq/signer-btc",
Incoherence between `@ledgerhq/signer-btc` and `@ledgerhq/device-signer-kit-ethereum`

2024-10-30 14:36 UTC, jdabbech-ledger commented
> Don't forget tu update the signer ethereum readme. Also I was thinking, we usr `btc`, `eth` but `solana` instead of `sol`. Should we plan to change this also ?

Yep thanks for the review.
IMO sol is more compliant indeed. Could change it in this PR if it's ok for @LedgerHQ/live-devices

2024-10-30 14:54 UTC, aussedatlo commented on packages/signer/signer-eth/README.md
> +const { observable, cancel } = signerETH.getAddress(derivationPath, options);
[ASK] Did you mean `SignerEth` instead of `SignerETH` ?

2024-10-30 15:15 UTC, jdabbech-ledger commented on packages/signer/signer-eth/README.md
> +const { observable, cancel } = signerETH.getAddress(derivationPath, options);
yes nice catch the variable is named `signerEth`

2024-10-30 15:22 UTC, aussedatlo approved these changes
LGTM 👍

2024-10-30 15:57 UTC, mbertin-ledger requested changes

2024-10-30 15:57 UTC, mbertin-ledger commented on danger/helpers.ts
> +        `^(${BRANCH_PREFIX.join("|")})\/((dsdk|l?dmk)-[0-9]+|no-issue|issue-[0-9]+)\-.+`,
[Comment] No need as Jira project is still DSDK

2024-10-30 15:57 UTC, mbertin-ledger commented on packages/core/package.json
[MUST] Whole package could be rename from `core` to `device-managemen-kit`

2024-10-31 14:17 UTC, mbertin-ledger approved these changes

2024-10-31 14:20 UTC, merged