✨ (signer-solana) [DSDK-566]: Add solana SignMessageUseCase
LedgerHQ/device-sdk-ts pull request #467
Opened 2024-11-04 11:04 UTC by fAnselmi-Ledger

### 📝 Description

Added Solana SignMessageUseCase

### ❓ Context

- **JIRA or GitHub link**: [DSDK-566](https://ledgerhq.atlassian.net/browse/DSDK-566)

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [x] **Covered by automatic tests** 
- [x] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-11-12 09:22 UTC, aussedatlo requested changes

2024-11-12 09:22 UTC, aussedatlo commented on packages/signer/signer-solana/src/internal/DefaultSignerSolana.ts
> +      .execute(_derivationPath, _message);
[COULD] Remove `_` for `derivationPath` and `message`, it's used for the linter to avoid warning on unused variable, but now they are used.

2024-11-12 09:22 UTC, aussedatlo commented on packages/signer/signer-solana/src/internal/app-binder/command/SignOffChainMessageCommand.test.ts
> +      derivationPath: "m/44'/501'/0'/0'",
[ASK] Not sure with solana, but with ether app derivation paths starting with `m` are invalid

2024-11-12 09:22 UTC, aussedatlo commented on packages/signer/signer-solana/src/internal/app-binder/device-action/SignMessage/SignMessageDeviceAction.ts
> +        } else {
[SHOULD] Now we don't have to split a message in chunk, we should get a signature on the command response. If we don't have any signature we should return an error.

I think this part is not necessary because we need to adapt the command to not return a `Maybe<Signature>` but a `Signature`.

2024-11-12 09:22 UTC, aussedatlo commented on packages/signer/signer-solana/src/internal/app-binder/task/SendSignMessageTask.ts
> +  private hf: HelperFunctions = {
[COULD] use `private buildFullMessage` to declare the function rather than creating a private helper

2024-11-12 09:22 UTC, aussedatlo commented on packages/signer/signer-solana/src/internal/app-binder/task/SendSignMessageTask.ts
> +      const lengthBytes = new Uint8Array(4);
[COULD] use `const` variable for numbers like `4`

2024-11-12 09:22 UTC, aussedatlo commented on packages/signer/signer-solana/src/internal/app-binder/task/SendSignMessageTask.ts
> +        fullMessage.length + 1 + 1 + numberOfDerivations * PATH_SIZE,
[COULD] same for `1`

2024-11-12 09:22 UTC, aussedatlo commented on packages/signer/signer-solana/src/internal/app-binder/task/SendSignMessageTask.ts
> +      paths.forEach((path) => {
[COULD] you can use

```ts
paths.forEach((path) => {
  builder.add32BitUIntToData(path);
});
```

2024-11-12 09:22 UTC, aussedatlo commented on packages/signer/signer-solana/src/internal/use-cases/message/SignMessageUseCase.ts
> +  private _appBinding: SolanaAppBinder;
[SHOULD] Rename `_appBinding` to `_appBinder`

2024-11-12 10:10 UTC, fAnselmi-Ledger commented on packages/signer/signer-solana/src/internal/app-binder/task/SendSignMessageTask.ts
> +  private hf: HelperFunctions = {
@aussedatlo I used the object to make a clearer distinction between args calls and internal functions

2024-11-12 10:44 UTC, aussedatlo commented on packages/signer/signer-solana/src/internal/app-binder/task/SendSignMessageTask.ts
> +  private hf: HelperFunctions = {
Sometimes we use the`_` prefix to make a clearer distinction but it mostly used with private attribute, we have few cases where it's used with a private function

2024-11-15 10:25 UTC, aussedatlo approved these changes

2024-11-15 10:58 UTC, merged