:sparkles: (dmk) [DSDK-542]: Add API calls and models for secure channel
LedgerHQ/device-sdk-ts pull request #469
Opened 2024-11-04 11:38 UTC by jdabbech-ledger

### 📝 Description

Manager api calls for secure channel 

### ❓ Context

- **JIRA or GitHub link**: [DSDK-542]

- **Feature**:

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [x] **Covered by automatic tests** 
- [x] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-11-05 08:43 UTC, jdabbech-ledger commented on packages/device-management-kit/src/internal/manager-api/model/Firmware.ts
> +  description: string | null | undefined;
As it's a model that comes from API, I guess yes.

2024-11-05 08:48 UTC, jdabbech-ledger commented on packages/device-management-kit/src/api/command/os/GetOsVersionCommand.ts
> +    const targetId = parseInt(
To convert the hexastring to a decimal string
 I could add a parser method for this

2024-11-05 09:00 UTC, aussedatlo commented on packages/device-management-kit/src/internal/manager-api/model/Firmware.ts
> +  description: string | null | undefined;
Is there any API doc for this endpoint ?

2024-11-05 09:33 UTC, jdabbech-ledger commented on packages/device-management-kit/src/internal/manager-api/model/Firmware.ts
> +  description: string | null | undefined;
Not that I know of, this type is the same in LL

2024-11-06 15:23 UTC, aussedatlo commented on packages/device-management-kit/src/internal/manager-api/model/Firmware.ts
> +  description: string | null | undefined;
Yeah I was thinking if the null is really useful here or needed for the business logic on the LL side

2024-11-25 15:26 UTC, valpinkman requested changes

2024-11-25 15:26 UTC, valpinkman commented on packages/device-management-kit/src/api/command/os/GetOsVersionCommand.test.ts
> +import { getOsVersionCommandResponseStubBuilder } from "./__mocks__/GetOsVersionCommand";
```suggestion
import { getOsVersionCommandResponseMockBuilder } from "./__mocks__/GetOsVersionCommand";
```

2024-11-25 15:26 UTC, valpinkman commented on packages/device-management-kit/src/api/command/os/GetOsVersionCommand.test.ts
> +          data: getOsVersionCommandResponseStubBuilder(DeviceModelId.NANO_X),
```suggestion
          data: getOsVersionCommandResponseMockBuilder(DeviceModelId.NANO_X),
```

2024-11-25 15:26 UTC, valpinkman commented on packages/device-management-kit/src/api/command/os/__mocks__/GetOsVersionCommand.ts
> +export const getOsVersionCommandResponseStubBuilder = (
```suggestion
export const getOsVersionCommandResponseMockBuilder = (
```

2024-11-25 15:26 UTC, valpinkman commented on packages/device-management-kit/src/internal/manager-api/data/__mocks__/GetDeviceVersion.ts
[SHOULD] Either you mock GetDeviceVersion (we should be placed wherever the real GetDeviceVersion is) or you need to change the name of this file

2024-11-25 15:26 UTC, valpinkman commented on packages/device-management-kit/src/internal/manager-api/data/__mocks__/GetFirmwareVersion.ts
[SHOULD] same here

2024-11-25 15:26 UTC, valpinkman commented on packages/device-management-kit/src/internal/manager-api/service/DefaultManagerApiService.test.ts
> +import { getOsVersionCommandResponseStubBuilder } from "@api/command/os/__mocks__/GetOsVersionCommand";
```suggestion
import { getOsVersionCommandResponseMockBuilder } from "@api/command/os/__mocks__/GetOsVersionCommand";
```

2024-11-25 16:28 UTC, jdabbech-ledger commented on packages/device-management-kit/src/internal/manager-api/model/Firmware.ts
> +  description: string | null | undefined;
IMO it's a bit over-engineered to do so, as the dmk doesn't manage the device firmware.
Those manager api calls aim to setup a secure channel by using only the fields `BaseFirmware.perso` and `GetDeviceVersion.id`.
Deleting useless fields is probably clearer than declaring and mapping them for nothing, wdyt?

2024-11-26 09:44 UTC, ofreyssinet-ledger commented on packages/device-management-kit/src/internal/manager-api/model/Firmware.ts
> +  description: string | null | undefined;
My 2 cents let's keep the model that comes from the API, then when we need more than the two fields (when the DMK will handle firmware updates) we will do an internal mapping.

2024-11-26 09:45 UTC, ofreyssinet-ledger approved these changes

2024-11-26 09:55 UTC, jiyuzhuang commented on packages/device-management-kit/src/internal/manager-api/data/__mocks__/GetDeviceVersion.ts
I'm not sure whether I understand, you mean renaming like `GetDeviceVersionMock.ts` ?

2024-11-28 10:50 UTC, valpinkman approved these changes

2024-11-28 11:01 UTC, merged