:recycle: (dmk) [DSDK-571]: Refactor ListDeviceSession into ListConnectedDevice
LedgerHQ/device-sdk-ts pull request #477
Opened 2024-11-06 14:06 UTC by jdabbech-ledger

### 📝 Description

- Remove `ListDeviceSessionsUseCase`
- Create `ListConnectedDevicesUseCase` and `ListenToConnectedDeviceUseCase`
- Update Sample app
- Update `ConnectedDevice` model to add `sessionId`

### ❓ Context

- **JIRA or GitHub link**: [DSK-591]

- **Feature**:

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [x] **Covered by automatic tests** 
- [x] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-11-06 14:51 UTC, mbertin-ledger requested changes

2024-11-06 14:51 UTC, mbertin-ledger commented on packages/device-management-kit/src/api/transport/model/ConnectedDevice.ts
> +    this.sessionId = sessionId;
[SHOULD] As id is useless, maybe we should remove id field from `ConnectedDevice` model ?

2024-11-06 17:09 UTC, jdabbech-ledger commented on packages/device-management-kit/src/api/transport/model/ConnectedDevice.ts
> +    this.sessionId = sessionId;
It's actually used by the hook `useAvailableDevice` of the sample app to match a discovered device to a connected device in order to have the `connected` status of an available device

2024-11-07 10:47 UTC, valpinkman commented on packages/device-management-kit/src/internal/discovery/use-case/ListenToConnectedDeviceUseCase.test.ts
> +    observable.subscribe({
[ASK] is this observable completing ? if not t means we have leakage in the tests

2024-11-07 16:39 UTC, mbertin-ledger approved these changes

2024-11-07 16:39 UTC, mbertin-ledger commented on packages/device-management-kit/src/api/transport/model/ConnectedDevice.ts
> +    this.sessionId = sessionId;
Ok. not a big fan but ok

2024-11-08 10:41 UTC, merged