📝 (doc) [NO-ISSUE]: Update documentation after feedbacks
LedgerHQ/device-sdk-ts pull request #483
Opened 2024-11-08 13:52 UTC by mbertin-ledger

### 📝 Description
 
Update documentation after reviews

### ❓ Context

Dev portal documentation 

- **Feature**:

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [ ] **Covered by automatic tests** 
- [ ] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-11-08 14:09 UTC, valpinkman commented on apps/docs/pages/docs/docs.mdx
> +Throughout all the documentation we will use several acronymes that you can find the following description :
[TYPO] acronyms

2024-11-08 14:11 UTC, valpinkman commented on apps/docs/pages/docs/explanations/dmk.mdx
> +- `locked`: The device is locked. User needs to unlock it.
It's weird to add "User needs to unlock it", either you add something like "User needs to unlock it to perform operations with the DMK" (or something like that),or we remove that sentence

2024-11-08 14:12 UTC, valpinkman commented on apps/docs/pages/docs/explanations/ledgerjs.mdx
> +Some device behavior are not well handled by the libraries, for example opening an application on the device will cause unexpected disconnection.
"not well" => "not correctly"

2024-11-08 14:13 UTC, valpinkman requested changes
Few typos and some some comments but overall nice

2024-11-08 15:27 UTC, smartine-ledger approved these changes

2024-11-12 09:53 UTC, valpinkman approved these changes

2024-11-19 10:15 UTC, merged