✨ (btc-signer) [DSDK-465]: Add GetWalletAddressCommand
LedgerHQ/device-sdk-ts pull request #512
Opened 2024-11-20 10:44 UTC by fAnselmi-Ledger

### 📝 Description

Added GetWalletAddressCommand

### ❓ Context

- **JIRA or GitHub link**: [DSDK-465](https://ledgerhq.atlassian.net/browse/DSDK-465)

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [x] **Covered by automatic tests** 
- [x] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

[DSDK-465]: https://ledgerhq.atlassian.net/browse/DSDK-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-20 11:08 UTC, jdabbech-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/utils/bitcoinAppErrors.ts
> +  implements DmkError
`class  BitcoinAppCommandError extends DeviceExchangeError<BitcoinAppErrorCodes> { constructor(args: CommandErrorArgs<BitcoinAppErrorCodes>) { super(...) }}` should be enough, no need to add a customerrorcode imo

2024-11-20 15:18 UTC, paoun-ledger commented on packages/signer/signer-btc/src/api/app-binder/GetWalletAddressCommandTypes.ts
> +  readonly display: 0 | 1;
[COULD] since it's an external API, I think types don't need to match the APDU, here it could just be a boolean to make it more clear

2024-11-20 15:19 UTC, paoun-ledger commented on packages/signer/signer-btc/src/api/app-binder/GetWalletAddressCommandTypes.ts
> +  readonly walletId: Buffer;
[COULD] We usually use UInt8Array everywhere instead of Buffer to make sure it's compatible with all environments, so it's not consistent with other apis to have buffers here

2024-11-20 16:09 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/GetWalletAddressCommand.ts
> +    builder.addBufferToData(Buffer.from([this.args.display]));
[COULD] Same here you could just use `Uint8Array.from` instead of `Buffer.from`

2024-11-21 09:20 UTC, jiyuzhuang commented on .changeset/quiet-feet-leave.md
> +Added GetWalletAddressCommand
Present tense in change log ?

2024-11-21 09:25 UTC, jiyuzhuang commented on packages/signer/signer-btc/src/internal/app-binder/command/GetWalletAddressCommand.ts
> +  }
```suggestion
  constructor(private readonly args: GetWalletAddressCommandArgs) {}
```
This will have the same effect and more clear, you can access to the property by `this.args` just as in the other places (most) in the code base.

2024-11-21 09:30 UTC, jiyuzhuang commented on packages/signer/signer-btc/src/internal/app-binder/command/GetWalletAddressCommand.ts
> +  }
This APDU construction can be put in the chain as:
```ts
  return new ApduBuilder({...})
    .addXYZ(...)
    .addABC(...)
    .build();
```
This pattern should be taken if possible.

2024-11-21 09:47 UTC, fAnselmi-Ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/utils/bitcoinAppErrors.ts
> +  B000: { message: "Wrong response length (buffer size problem)" },
@paoun-ledger lint:)

2024-11-21 13:08 UTC, paoun-ledger commented on packages/signer/signer-btc/src/api/app-binder/GetWalletAddressCommandTypes.ts
> +export type GetWalletAddressCommandArgs = {
[SHOULD] sorry I didn't notice at first, but signers commands should not be exposed in the api, it can remain internal. The commands cannot be easily used by end users since they require opening the app, waiting user interactions, using internal stuff such as merkletrees and tasks, ...

We already expose higher level apis such as `getAddress` of the `SignerBtc`, which will call that command internally

2024-11-21 13:14 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/GetWalletAddressCommand.test.ts
> +    ]);
[COULD] not sure what others think but for those kind of tests, I usually prefer to assert against a hardcoded buffer containing directly the expected apdu. Because here you almost reproduce the code of the function you're testing :sweat_smile: 
Something like that: https://github.com/LedgerHQ/device-sdk-ts/blob/develop/packages/signer/signer-eth/src/internal/app-binder/command/GetAddressCommand.test.ts#L9

2024-11-21 15:47 UTC, paoun-ledger commented on packages/signer/signer-btc/src/api/app-binder/GetWalletAddressCommandTypes.ts
> +export type GetWalletAddressCommandArgs = {
not yet resolved I think since that file was not removed ? :sweat_smile:

2024-11-21 16:11 UTC, jdabbech-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/GetWalletAddressCommand.ts
> +    if (isCommandErrorCode(errorCode, bitcoinAppErrors)) {
checking bitcoin error code is not enough, a `GLOBAL_ERROR` like `0x5515 (Device locked)` could happen here

2024-11-21 16:53 UTC, fAnselmi-Ledger commented on packages/signer/signer-btc/src/api/app-binder/GetWalletAddressCommandTypes.ts
> +export type GetWalletAddressCommandArgs = {
@paoun-ledger MB forgot to remove the file, thanks for checking in!

2024-11-25 09:09 UTC, jdabbech-ledger approved these changes

2024-11-25 09:14 UTC, paoun-ledger approved these changes
lgtm

2024-11-25 09:20 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/GetWalletAddressCommand.ts
> +      p2: 0x00,
[SHOULD] Actually after reading the reference implementation, I noticed p2 was set to 1 for all commands : https://github.com/LedgerHQ/app-bitcoin-new/blob/master/bitcoin_client_js/src/lib/appClient.ts#L89

And actually that was documented in the readme:

> The P1 field is reserved for future use and must be set to 0 in all messages. The P2 field is used as a protocol version identifier; the current version is 1, while version 0 is still supported. No other value must be used.

For now I think you can force support of version 1. If we need to support legacy apps, we may think about it later. In that case we should set p2=1 for all bitcoin commands :)

2024-11-25 09:21 UTC, paoun-ledger requested changes
sorry I didn't notice previously that p2 should contain a protocol version...

2024-11-25 16:27 UTC, paoun-ledger approved these changes
lgtm

2024-11-25 16:39 UTC, merged