:sparkles: (signer-btc) [DSDK-466]: Implement RegisterWallet Command
LedgerHQ/device-sdk-ts pull request #516
Opened 2024-11-21 13:53 UTC by jdabbech-ledger

### 📝 Description

Implement RegisterWallet Command

### ❓ Context

- **JIRA or GitHub link**: [DSDK-466]

- **Feature**:

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [x] **Covered by automatic tests** 
- [x] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-11-22 08:15 UTC, fAnselmi-Ledger requested changes

2024-11-22 08:15 UTC, fAnselmi-Ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/RegisterWalletAddressCommand.test.ts
> +import {
This test seems leaky 💧 give a try running with `--detectLeaks` flag.

2024-11-22 08:15 UTC, fAnselmi-Ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/RegisterWalletAddressCommand.ts
> +
we can first merge `feat/DSDK-465-ts-signer-implement-get-wallet-address-command` so you can add BTC error handling here, WDYT?

2024-11-22 13:57 UTC, fAnselmi-Ledger approved these changes

2024-11-25 09:08 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/RegisterWalletAddressCommand.ts
> +    return (
Actually there was already a wallet policy serializer service here: https://github.com/LedgerHQ/device-sdk-ts/blob/develop/packages/signer/signer-btc/src/internal/wallet/service/DefaultWalletSerializer.ts#L29

I did it because many commands require a wallet ID, which is a hash of the serialized wallet so I thought it was better to centralize it in a service.
If that seems good for you, that command could just take a serialized array in parameters :smile:

2024-11-25 09:23 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/RegisterWalletAddressCommand.ts
> +      p2: 0x01,
[COULD] detail but maybe it could be put in a global contant for all bitcoin commands, since it's a protocol version ?

2024-11-25 09:47 UTC, jdabbech-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/RegisterWalletAddressCommand.ts
> +      p2: 0x01,
yes it sounds good

2024-11-25 12:14 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/utils/constants.ts
> +export const WALLET_POLICY_V1 = 1;
I think those are not the same. The wallet policy (currently 0x02) is used for the wallet serialization.
Here it's the bitcoin app protocol version, not the wallet version, as described here: https://github.com/LedgerHQ/app-bitcoin-new/blob/master/doc/bitcoin.md

> The P2 field is used as a protocol version identifier; the current version is 1, while version 0 is still supported. No other value must be used.

2024-11-25 14:02 UTC, merged