✨ (signer-btc): Implement clientCommands
LedgerHQ/device-sdk-ts pull request #528
Opened 2024-11-29 09:49 UTC by fAnselmi-Ledger

### 📝 Description

Implemented ClientCommandInterpreter and client command handlers

### ❓ Context

- **JIRA or GitHub link**: [DSDK-462](https://ledgerhq.atlassian.net/browse/DSDK-462)

### ✅ Checklist

Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is not yet ready for review.

- [x] **Covered by automatic tests** 
- [x] **Changeset is provided** 
- [ ] **Impact of the changes:** 
  - _list of the changes_

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.

2024-12-03 16:28 UTC, jdabbech-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/utils/ClientCommandInterpreter.ts
> +  public unsafeManuallySetQueue(queue: Uint8Array[]): void {
[could] remove it ?

2024-12-04 09:10 UTC, fAnselmi-Ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/utils/ClientCommandInterpreter.ts
> +  public unsafeManuallySetQueue(queue: Uint8Array[]): void {
thanks! yes, that is not used anymore

2024-12-04 16:11 UTC, mbertin-ledger requested changes
Not sure about this implementaiton, in my opinion, I would prefer to avoid send APDU with the commands handlers. Moreover the interpreter seems to be more a service than a utils. Can we see it together (with @jdabbech-ledger @paoun-ledger @fAnselmi-Ledger) ?

2024-12-13 12:52 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/client-command-handlers/GetPreimageCommandHandler.ts
> +    response.set(preimage.slice(0, bytesToIncludeInResponse), responseOffset);
Instead of building the buffer manually, we already have a `ByteArrayBuilder` in device-management-kit.
Something like:

    const response = new ByteArrayBuilder()
        .addBufferToData(addBufferToData)
        .add8BitUIntToData(bytesToIncludeInResponse)
        .addBufferToData(preimage.slice(0, bytesToIncludeInResponse))
        .build();

2024-12-13 13:01 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/client-command-handlers/GetMerkleLeafProofCommandHandler.ts
> +  const parser = new ByteArrayParser(request.slice(33));
instead of using `33` magic number, you could re-use your constant `BUFFER_SIZE`.
By the way `BUFFER_SIZE` is not clear enough since we have other kind of buffers :sweat_smile: 
Isn't it rather a `HASH_SIZE`, or even a `SHA256_SIZE`?

2024-12-13 13:15 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/client-command-handlers/GetMerkleLeafProofCommandHandler.ts
> +          context.queue.push(proof[remainingProofElementIndex] as Uint8Array);
you can probably factorize those chunking logics which are used in several handlers

2024-12-13 13:17 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/client-command-handlers/GetMerkleLeafProofCommandHandler.ts
> +  const rootHash = request.slice(1, BUFFER_SIZE + 1);
you can start using the ByteArrayParser from here  to extract the root hash, since it's used anyway from next line :smile:

2024-12-13 13:20 UTC, paoun-ledger commented on packages/signer/signer-btc/src/internal/app-binder/command/client-command-handlers/GetMerkleLeafProofCommandHandler.ts
> +          context.queue.push(proof[remainingProofElementIndex] as Uint8Array);
ah not sure it can really be factorized actually since it is chunked per hash size in that case, and not per byte

2024-12-18 08:59 UTC, closed without merging